### ISSUE TITLE
Fix Background and animation

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#115]
If you use `Fix background` to freeze the image background on the animation. And `Copy to all frames`, it duplicate on all frames.

This makes it possible to draw the animation and then erase errors, without losing the background. It's perfect. 👍 

![image](https://github.com/mriale/PyDPainter/assets/130657737/460eb010-dc95-4fef-a470-8f57638ce84b)

But when you free the background, you've also lost the background on all frames other than the current one. 😭 

![image](https://github.com/mriale/PyDPainter/assets/130657737/e20624cf-9143-411b-b915-07efcda667c2)

This damn program won't let me finish my animation tutorial, ever! 🤣

**Comment by mriale** [comment]
I just tried this in Deluxe Paint III, and background with animation is not very useful because there is only one foreground as you switch among the frames. The foreground gets stamped down on one frame when you free the background.

In this world with almost infinite memory, I think I want to add a background for each frame. That would also pave the way for rotoscoping over reference animations.

**Comment by mriale** [comment]
Commit 0eb984b3c0641364629b9aa1cf64df083dd4b1a5 fixed background functionality with animation by implementing with the new layer engine.
