### ISSUE TITLE
Smooth mode drawing as usual with background color

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#135]
change your background color to another color than black and clear screen (CLR)

![image](https://github.com/mriale/PyDPainter/assets/130657737/eac657ae-41b7-43df-9679-25161caef7c2)

Draw something. Hit F8. Smooth your drawing. Fine.
Click the 0 color (black). It now draw as if black was the foreground color in Color Mode.
Or as if black (0) still was the background color in Smooth Mode.
Click any other color. Back to normal. Erase with new background color. Smooth draw with left click.

It has another behavior in dev version.

**Comment by mriale** [comment]
Thanks for finding this! I hadn't seen that before.

Issue #127 is the reason for the behavior in the last release that just draws with the background color instead of applying the brush mode.

With that issue fixed in `develop`, another problem showed up when drawing with the background color. It turns out that to draw with the background color, the transparent color of the brush ends up not being the same as the background color of the brush. I made it look at the transparent color of the brush instead of the background color and then it worked as expected.

**Comment by Sleuthgame** [comment]
I'm glad to see it fixed! Already !
I found it because I record some video tutorial.

**Comment by Sleuthgame** [comment]
It's ok now. We can close the ticket. :-)
