### ISSUE TITLE
SHIFT while drawing rectangle

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#138]
Holding **SHIFT** while using **Rectangle** tool does not fit the Dpaint legacy:

```
Incidentally, if you hold down the Shift key as you draw, you can
constrain the rectangle so that its height and width are equal. 
```

**Comment by Sleuthgame** [comment]
Same for **Brush** selector.

**Comment by mriale** [comment]
Added shift to constrain to square for rectangle tool and brush tool. In the process I had to modify the event handlers because holding shift was auto-repeating the key press and causing the rectangles to flash repeatedly. Issue #142 fixed that and also made a way for future automated testing and scripting (issue #130).

**Comment by Sleuthgame** [comment]
Ready to go. I have updated the doc.
