### ISSUE TITLE
Animpaint FILL (productivity enhancement)

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#177]
Add Animpainting function to **FILL tool**.

Working on a animation, you can have areas to fill over the entire animation. Sometime to fill a sky with a gradient, color a shape, fill the gap from importing video files than are not 100% your final PydPainter screen format. Having to fill a thousand frames animation is relaxing but boring.

Clicking with Animpainting key shoud fill the area from the same origin point for a bunch of frames* (let's say 10 by default or custom parameter).
![image](https://github.com/user-attachments/assets/8fc1912f-013a-4139-b043-77dd752ef292)
Example: Video file was exported to a 320x240 pixel height (can't be better), so in PAL, it miss 16 pixels on top **and** bottom. But on top of that, there were the black edges of a cinema format. So as you can imagine, that means 268 clicks on the `next image` key and then on `Fill`. Twice (bottom and top area).

**Comment by Sleuthgame** [comment]
* having the fill over the entire animation only, may not be so usefull. For example, in the case of filling a shape that moves on the screen. Or even when filling a background, there are always exceptions (a text that moves in front, fade in/out).
There are always exceptions for a few frames.

**Comment by mriale** [comment]
You could accomplish the same thing by doing this:
* Switch to the spare page using the `j` key
* Draw rectangles to cover the area you want to fill on the video
* Press `j` to get back to the video
* Select in the menu: Picture -> Spare -> Merge in back

This should work for any range of frames since it prompts for which frames to include.

I'm not sure animpainting makes sense for fill since the mouse would not be moving like with the other animpainting tools.

**Comment by Sleuthgame** [comment]
Thanks ! I always forgot about merge in back. I should record some tutorial.

**Comment by Sleuthgame** [comment]
If you want to color a moving sketch / scanned animation like this, it may be usefull :
https://www.randelshofer.ch/animations/anims/magnus_ahlvik/Man&Dog.anim.html
