### ISSUE TITLE
Windows seems to find malware in the release 1.0.6 executable

### ISSUE THREAD

**Issue by MetinSeven** [mriale/PyDPainter#34]
Hi Mark,

Thanks for the 1.0.6 update of PyDPainter. My antivirus found a wacatac.b!ml trojan in the executable though, so I thought to let you know. Don't know if it's a false positive, but just to be sure I won't open the executable.

**Comment by MetinSeven** [comment]
Over at Virustotal, only one entry thinks it's malware:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/18738261/230888025-60e04b4a-ce37-449e-85d1-5d7f2340d1ce.png">

**Comment by mriale** [comment]
Anti-virus programs might flag PyDPainter as malware because a lot of malware is Python scripts packaged with PyInstaller to make executables. If I were to buy an expensive code signing key and then not change my code very often, it could build up a reputation as not malware. That's not a very good option for small open source projects that are updated often, though. Sorry I don't have a good option here, but thanks for letting me know.

**Comment by Sleuthgame** [comment]
It's something like this ?
https://comodosslstore.com/code-signing
How expensive it is !
