### ISSUE TITLE
Shear, bend and outline custom brush lost background color

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#54]
![image](https://user-images.githubusercontent.com/130657737/234693244-1994abc6-aff6-4703-bc83-0193f266d42d.png)

1. Change background to a color (ie: green)
2. Draw something like a tree or cloud
3. Select a brush of your cloud. Background is still green, your brush transparency is okay.
4. Use Shear or Bend or Outline with the brush.
Custom transparency is lost and a there is a black area surrounding the box.

Sorry for the bad news. Good luck !

**Comment by Sleuthgame** [comment]
1.0.8 and 1.0.9 (dev)

**Comment by mriale** [comment]
Awesome find! Never feel bad about reporting a bug. It only makes the software better. I hadn't seen this in my own testing because I generally leave color 0 as the background. Thank you so much for finding this and giving me a clear instructions to recreate it. I fixed it in the develop branch with 3 lines of code.

**Comment by Sleuthgame** [comment]
Hi !

Still a bug with [o] **outline** brush. With any colored background other than default black.
Tested in 1.0.9 and 1.0.10 dev

**Comment by mriale** [comment]
Thanks for tracking that down!
Fixed now in `develop` version 1.0.10 dev.
