### ISSUE TITLE
Gradient from center. Stopped by the edges

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#57]
![image](https://user-images.githubusercontent.com/130657737/235886736-35cd1042-dc4b-4e92-a548-9b8b90b914c4.png)
As you see the gradiant calculation is stopped by the edges of the canvas. Ovales and Circles. 1.0.10 dev.

It is not consistent with other filling modes that continue off screen.

But it's nice too, not really a bug.

**Comment by Sleuthgame** [comment]
![image](https://user-images.githubusercontent.com/130657737/235888760-e9a15912-ac59-472e-ab53-595975c6b12a.png)
And Fill tool too.

**Comment by MetinSeven** [comment]
I think it should remain this way. The shape dictates the gradient, also at the edges.

**Comment by mriale** [comment]
I turned off clipping for fill from center and also the vertical gradient so the gradients for shapes are calculated beyond the edge of the screen. If you want the fill mode for shapes to be constrained to the edges of the screen, you can first draw with a solid color and then use the flood fill tool to fill with a gradient for the same effect.

The flood fill tool remains constrained to the edges of the screen because I'm not quite sure what else it makes sense to do.

This is now in the `develop` branch version 1.0.10 dev.
