### ISSUE TITLE
Brush handling changes affect default brushes permanently

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#58]
1. Define a custom brush.
2. Change Handle to a corner (Alt-x). It works.
3. Go back to a default brush.
4. You're now handling it from a corner.
5. Try to go back. Using this brush in Center handling (alt-s) or another Corner (Alt-x) or even Place (Alt-z). Nothing works. :'(
![image](https://user-images.githubusercontent.com/130657737/236565676-22e0946b-982b-420f-93e1-ecb45317ff32.png)

**Comment by Sleuthgame** [comment]
It looks like the Handle options have no effect on the default brushes. The problem is that changing the handling on a defined brush keeps this handle on the default brushes afterwards.

**Comment by mriale** [comment]
@Sleuthgame I guess I had never implemented handles for built-in brushes correctly. Thanks for finding that! This is fixed in the `develop` branch now. However there are some differences between the way DPaint and PyDPainter handle things:
- If you switch from a custom brush to a built-in brush or the other way around, PyDPainter resets the handle back to center. I think that makes more sense, but DPaint preserves the brush handle.
- The keyboard shortcut `alt-x` in PyDPainter moves the handle to all 4 corners in sequence. In DPaint, a combination of `alt-x` and `alt-y` are needed to move to all 4 corners. Maybe I could change that if anyone cared, but at this point I just left it.

Anyway, please take a look to make sure it doesn't glitch out weirdly after some strange sequence.

**Comment by Sleuthgame** [comment]
I'm totally fine with that. It makes more sense this way.
